### ISSUE TITLE
当数据量在1万+的时候，有什么优化的方法可以加速排序吗

### ISSUE THREAD

**Issue by cityleaf** [honeycao/SearchDemo#4]
对1万+ 的数据进行首字母排序时，耗时比较大，也使用了多线程后，有什么建议可以做到1秒内处理完

**Comment by honeycao** [comment]
和线程无关，只和排序算法有关，这里的排序是系统排序，估计不适合大数据了，大数据的排序得用其他的算法才行~~

**Comment by cityleaf** [comment]
> 和线程无关，只和排序算法有关，这里的排序是系统排序，估计不适合大数据了，大数据的排序得用其他的算法才行~~

对的，排序耗时：先检索，再组内排序，这两步确实很耗时。但是数据量两万了，目前是服务端排好，我们直接分组，秒出，网络请求也很快。
